#No perms message
msgNoPerms: "&cYou don't have permission to use this command"

#All possible enchantments
enchants:
  - "aqua_affinity"
  - "bane_of_arthropods"
  - "blast_protection"
  - "channeling"
  #- "binding_curse"
  #- "vanishing_curse"
  - "depth_strider"
  - "efficiency"
  - "feather_falling"
  - "fire_aspect"
  - "fire_protection"
  - "flame"
  - "fortune"
  #- "frost_walker"
  - "impaling"
  - "infinity"
  - "knockback"
  - "looting"
  - "loyalty"
  - "luck_of_the_sea"
  - "lure"
  - "mending"
  - "multishot"
  - "piercing"
  - "power"
  - "projectile_protection"
  - "protection"
  - "punch"
  - "quick_charge"
  - "respiration"
  - "riptide"
  - "sharpness"
  #- "silk_touch"
  - "smite"
  - "soul_speed"
  - "sweeping"
  - "swift_sneak"
  - "thorns"
  - "unbreaking"


